### ISSUE TITLE
[Fix] 디자인 안드 QA 반영

### ISSUE THREAD

**Issue by HELLOHIDI** [Indipage/PPPiOS#109]
## 🛠 Issue
- 디자인 안드 QA 반영

## 📋 To-do
- [ ] 티켓 이미지 변경
- [ ] 저장된 아티클 이미지
- [x] collectionView 이미지 추가하기
- [x] 아티클 제목이랑 버튼 이미지 바꾸기
