### ISSUE TITLE
[Fix] 서점 상세보기 뷰 수정사항

### ISSUE THREAD

**Issue by binisnil** [Indipage/PPPiOS#113]
## 🛠 Issue
- 서점 상세보기 뷰에서 수정사항을 반영합니다

## 📋 To-do
- [ ] 서점 상세보기 스크롤뷰 높이 문제 해결
- [ ] 서점 상세보기 큐레이션 데이터 바인딩 문제
- [x] 큐레이션 부분 책 터치하면 터치된 책이 가운데로 오도록 기능 추가
- [ ] 큐레이션 부분 빨리 스크롤 하더라도 한페이지 이상 넘어가지 않도록 수정
- [x] 서점 상세페이지 줄바꿈
- [ ] 아티클 - 서점 상세페이지 무한루프 문제
- [x] #이랑 텍스트 사이 간격 만들어주기

**Comment by HELLOHIDI** [comment]
언제 작업하냐 디질라고

**Comment by binisnil** [comment]
> 언제 작업하냐 디질라고

흠냐
