### ISSUE TITLE
[Feat] 온보딩 뷰 UI 작업 

### ISSUE THREAD

**Issue by HELLOHIDI** [Indipage/PPPiOS#119]
## 🛠 Issue
- 온보딩 뷰 UI 작업 

## 📋 To-do
- [x] 소셜로그인 뷰 UI 작업
- [x] 애플 소셜로그인 세팅
- [x] 온보딩 뷰 UI 작업
