### ISSUE TITLE
[Fix] 릴리즈 전 수정사항 작업

### ISSUE THREAD

**Issue by HELLOHIDI** [Indipage/PPPiOS#128]
## 🛠 Issue
- 릴리즈 전 수정사항 작업

## 📋 To-do
- [ ] 릴리즈 전 수정사항 작업
- [ ] 티켓 쪽 스크롤 이상부분 (안 되는건 아니고 그냥 더 잘되게) (류희재)
- [ ]  티켓 이미지 암튼 좀 이상함 (류희재)
- [ ]  카드 페이지 카드별 사이즈가 다릅니둥 (류희재)
- [ ]  저장된 아티클, 서점 비어있을 때 emptyView 넣어주기 (류희재)
- [ ]  로그아웃  (류희재)
