### ISSUE TITLE
[Fix] 1차 스프린트 수정사항

### ISSUE THREAD

**Issue by binisnil** [Indipage/PPPiOS#132]
## 🛠 Issue
- 버그 및 수정사항을 반영합니다

## 📋 To-do
**[SearchView]**
- [x] 검색 페이지 검색 x버튼
- [x] 스크롤 내려가 있는 상태로 검색하면 맨 위로 안올라오는 문제

[DetailView]
- [ ]  서점 상세보기 뷰 스크롤뷰 높이 문제 해결
- [ ]  서점 상세보기 큐레이션 데이터 바인딩 
- [ ]  추천서가 페이지 속도 조절하거나 멈추는 기능
- [ ]  아티클 - 서점 페이지를 무한루프 할 수 있는 상태
- [ ]  서점 상세페이지에서 추천서가 없으면 뷰 없애고 스크롤뷰 높이 줄이기
- [ ] 아티클로 넘어갔다가 다시 pop 하면 태그 쌓임
