### ISSUE TITLE
[Fix] 릴리즈 위한 오류수정

### ISSUE THREAD

**Issue by HELLOHIDI** [Indipage/PPPiOS#134]
## 🛠 Issue
- 릴리즈 위한 오류수정

## 📋 To-do
- [x] 티켓 쪽 스크롤 이상부분 (안 되는건 아니고 그냥 더 잘되게)
- [x] 티켓 이미지 암튼 좀 이상함
- [x] 카드 페이지 카드별 사이즈가 다름 이슈
- [x] 저장된 아티클, 서점 비어있을 때 emptyView 넣어주기
- [x] 로그아웃
