### ISSUE TITLE
[Style] 티켓 뷰 UI 구현

### ISSUE THREAD

**Issue by HELLOHIDI** [Indipage/PPPiOS#14]
## 🛠 Issue
-  티켓 뷰 UI 구현

## 📋 To-do
- [x] 티켓 뷰 UI 구현
- [x] 카드 뷰 UI 구현
- [x] 인증 성공 UI 구현
- [x] 인증 실패 UI 구현
