### ISSUE TITLE
[Style] HomeArticleView UI 구현

### ISSUE THREAD

**Issue by ena-isme** [Indipage/PPPiOS#17]
## 🛠 Issue
- [Style] HomeArticleView UI 구현

## 📋 To-do
- [ ] Footer View 구현
- [ ] Header View 구현
- [ ] Table Cell 구현
- [ ] NavigationBar 구현
