### ISSUE TITLE
[Setting] 프로젝트 세팅

### ISSUE THREAD

**Issue by HELLOHIDI** [Indipage/PPPiOS#3]
## 🛠 Issue
- 프로젝트 세팅

## 📋 To-do
- [x] .gitIgnore 설정
- [x] Extension 코드 추가
- [x] Storyboard 파일 삭제
- [x] 라이브러리 추가
- [x] 네트워크 커스텀 코드 추가
