### ISSUE TITLE
[Style] 티켓 애니메이션 구현 

### ISSUE THREAD

**Issue by HELLOHIDI** [Indipage/PPPiOS#37]
## 🛠 Issue
- 티켓 애니메이션 구현 

## 📋 To-do
- [x] 티켓, 카드 분기버튼 애니메이션 구현
- [x] 티켓 QR코드 체크화면 이동 애니메이션 구현
- [x] 카드 눌렸을 때 메소드 추가
