### ISSUE TITLE
[Style] DetailView 상세 UI 구현

### ISSUE THREAD

**Issue by binisnil** [Indipage/PPPiOS#48]
## 🛠 Issue
- DetailView의 상세 UI을 구현합니다 

## 📋 To-do
- [x] 저장 버튼 선택 시 색상 변화
- [x] 조르기 버튼 선택 시 색상 변화
- [x] collectionView 알파값 조정
- [x] collectionView paging기능 구현
