### ISSUE TITLE
[Network] 마이페이지 API 서버통신

### ISSUE THREAD

**Issue by HELLOHIDI** [Indipage/PPPiOS#51]
## 🛠 Issue
- 마이페이지 API 서버통신

## 📋 To-do
- [ ] 유저 정보 조회 API 서버통신
- [ ] 저장한 아티클 리스트 조회 API 서버통신
- [ ] 저장한 공간 리스트 조회 API 서버통신
