### ISSUE TITLE
[Network] 티켓뷰 API 서버통신

### ISSUE THREAD

**Issue by HELLOHIDI** [Indipage/PPPiOS#53]
## 🛠 Issue
- 티켓뷰 API 서버통신

## 📋 To-do
- [x] 방문하기 (QR 인식 성공) API 서버통신
- [x] 수령한 티켓 리스트 조회 API 서버통신
- [x] 방문한 카드 리스트 조회 API 서버통신
