### ISSUE TITLE
[Refactor] 티켓뷰 코드 리펙토링

### ISSUE THREAD

**Issue by HELLOHIDI** [Indipage/PPPiOS#59]
## 🛠 Issue
- 티켓뷰 코드 리펙토링

## 📋 To-do
- [ ] 티켓 관련 서버통신 코드 수정
- [ ] 티켓 QR코드 싱글톤 패턴으로 구현
- [ ] 티켓 애니메이션 코드 리팩토링
- [ ] 티켓 분기처리 코드 리팩토링
