### ISSUE TITLE
[Feat] DetailViewController 공간 북마크 관련 API 연동

### ISSUE THREAD

**Issue by binisnil** [Indipage/PPPiOS#61]
## 🛠 Issue
- 공간 북마크와 관련된 API 를 연동합니다

## 📋 To-do
- [ ]  공간 북마크 여부 조회
- [ ]  공간 북마크 등록하기
- [ ]  공간 북마크 취소하기
