### ISSUE TITLE
[Network] DetailViewController 공간 관련 API 연동

### ISSUE THREAD

**Issue by binisnil** [Indipage/PPPiOS#63]
## 🛠 Issue
- 공간 상세보기와 관련된 API 를 연동합니다

## 📋 To-do
- [x]  공간에 대한 아티클 조회 API 연동
- [x]  공간 상세조회 API 연동
- [x]  공간의 추천서가 조회 API 연동
- [x]  조르기 여부 조회 API 연동
- [x]  조르기 API 연동
