### ISSUE TITLE
[Network] 홈뷰 API 서버통신

### ISSUE THREAD

**Issue by ena-isme** [Indipage/PPPiOS#66]
## 🛠 Issue
- [Network] 홈뷰 API 서버통신 

## 📋 To-do
- [x] 전체 아티클 API 서버통신
- [x] 아티클 티켓 API 서버통신
- [x] 아티클 슬라이드 여부 API 서버통신
