### ISSUE TITLE
[Network] 아티클뷰 API 서버통신

### ISSUE THREAD

**Issue by ena-isme** [Indipage/PPPiOS#69]
## 🛠 Issue
- [Network] 아티클뷰 API 서버통신

## 📋 To-do
- [x] 티켓 수령 API 서버통신
- [x] 티켓 수령 여부 API 서버통신
- [x] 아티클 북마크 여부 API 서버통신
- [x] 아티클 북마크 등록 API 서버통신
- [x] 아티클 북마크 취소 API 서버통신
