### ISSUE TITLE
[Refactor] DetailViewController 오류 해결

### ISSUE THREAD

**Issue by binisnil** [Indipage/PPPiOS#71]
## 🛠 Issue
- DetailView에서 발생하는 문제들을 해결합니다
- DetailView 코드리뷰를 반영합니다

## 📋 To-do
- [x] 추천서가 CollectionView 가운데 정렬
- [x] collectionView Index out of range 에러 해결
- [x] TextView 데이터에 따라서 높이 조정 안되는 문제 해결
- [x] 추천서가 CollectionView 스크롤 전 데이터 반영 안되는 문제 해결
- [ ] 태그 CollectionViewCell 간격 조절

- [x] UIKit extension alpha 함수명 변경
- [x] 안쓰는 코드 지우기
