### ISSUE TITLE
[Fix] 아티클 뷰 오류 해결

### ISSUE THREAD

**Issue by HELLOHIDI** [Indipage/PPPiOS#76]
## 🛠 Issue
- 아티클 뷰 오류 해결

## 📋 To-do
- [ ] 각 테이블 뷰 셀 별로 간격을 지정해줘야 한다.
- [ ] link label을 클릭할 시 서점 상세페이지로 넘어가는 부분 구현
- [ ] 타이틀 또한 색상 적용하기
- [ ] line 케이스 추가하기
- [ ] 아티클만 관리하는 class 만들어서 관리하기
- [ ]  불필요한 코드 삭제 및 Enum 처리 하기
