### ISSUE TITLE
[Refactor] 전체적인 코드 리팩토링

### ISSUE THREAD

**Issue by HELLOHIDI** [Indipage/PPPiOS#90]
## 🛠 Issue
- 전체적인 코드 리팩토링

## 📋 To-do
- [ ] 애니메이션 싱글톤 패턴 구현
- [ ] QR 싱글톤 패턴 수정
- [ ] Article 싱글톤 패턴 수정
- [ ] 서버 통신 안되는 부분 수정
- [ ] 티켓 QR인식 서버통신 부분 수정
- [ ] 화면 전환시 탭바 유부 분기처리 구현
