### ISSUE TITLE
[Refactor] Home, Search View 기기대응 

### ISSUE THREAD

**Issue by binisnil** [Indipage/PPPiOS#91]
## 🛠 Issue
- 기기대응 및 필요없는 코드를 정리합니다

## 📋 To-do
- [x] 검색 headerView 지우기
- [ ] Home
    - [x] ticket case 크기
    - [x] ticket 크기
    - [x] ticket title이 ticket 넘어가는 현상
    - [x] HomeAllView -> 스크롤 맨 아래까지 안됨
    - [x] MySavedArticleCollectionViewCell -> subTitleLabel cell 밖으로 넘어감
