### ISSUE TITLE
[Refactor] - 전체적인 에러 수정 & 기능 추가

### ISSUE THREAD

**Issue by HELLOHIDI** [Indipage/PPPiOS#94]
## 🛠 Issue
- 전체적인 에러 수정 & 기능 추가

## 📋 To-do
- [ ] home 아티클 전체 조회에서 아티클 들어가면 아티클 안나옴
- [ ] 검색 뷰에서 검색하고 → 지우면 전체 조회 안됨
- [ ] 아티클 한개 문단에서 두개 처리 안됨
- [ ] 카드 이미지 거꾸로 나오는거 고쳐야됨
- [ ] 아티클, 서점 그래픽 추가해야됨
- [ ] 마이페이지 셀렉트처리 none으로 바꿔야됨
- [ ] 검색 공간, 저장공간 마찬가지 → "Attempted to scroll the collection view to an out-of-bounds item (1) when there are only 0 items in section 0. 이 에러 해결해야 함
- [ ] 티켓, 카드 버튼 두번 누르면 분기처리 깨짐
- [ ] 아티클 저장이 안 먹힘
- [ ] 홈 뷰 애니메이션 싱글톤 패턴 구현
- [ ] Article 싱글톤 패턴 수정
- [ ] 앱 아이콘 이름 등록하기
- [ ] 아티클에서 홈으로 돌아올 때 탭바 사라짐
- [ ] splash 화면
