### ISSUE TITLE
[Refactor] Detail, My 기기대응

### ISSUE THREAD

**Issue by binisnil** [Indipage/PPPiOS#95]
## 🛠 Issue
- Detail, My 기기대응
## 📋 To-do
- [ ] Ticket
    - [ ] Ticket Toggle View 토글 길이 안맞음
    - [ ] SE에서collectionView 하단 스크롤 영역 inset
- [x] My
    - [x] se에서 scroll 하단 스크롤 끝까지 안됨
- [x] Detail
    - [x] 아티클 읽으러가기 버튼 SE에서 조금 찌그러짐
    - [x] 아티클 읽으러가기 View subtitle 이 View 넘어감
    - [x] 아티클 읽으러가기 View 사진 cornerRadius 적용 안됨
