### ISSUE TITLE
[Fix] HomeView 에러 수정

### ISSUE THREAD

**Issue by ena-isme** [Indipage/PPPiOS#99]
## 🛠 Issue
- [Fix] HomeView 에러 수정

## 📋 To-do
- [x] 티켓 슬라이드 여부에 따라 HomeView 다르게 분기처리
- [x] CollectionView 위 버튼이 있을 시 스크롤 되도록 수정
- [x] CollectionView 위치 기기 대응
- [x] 아티클 Id 에 따라 해당 아티클로 전환되도록 수정
